# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dff7400a4a078e0e15b879d278774e18a7f4f66fdf69fc0e545458c86f0b9b164ae0f4baecfa5dd497f177f6330f9d1810ce8a61b2b53181e45cf24117b3ff4a

test:
  secret_key_base: 2c4a165d687b59e2172c341d8ffdaa20725ba2bc23c2934ac1fa70ff4ef6734a8d7a8729b475e4ff8075b6709e0f18ba13afde61812a45fe05721cae193446a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
